image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build

build:
  stage: build
  script:
    - &install-sshpass apk upgrade && apk update && apk add openssh-client && apk add sshpass
    - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_URL "cd internship-deploy && git pull"