
version: '3.3'


services:
    web:
        container_name: proxy
        network_mode: "host"        
        restart: on-failure
        image: registry.gitlab.com/prime-int/mentors/internship-team/internship-proxy:main
        volumes:
            - ./src:/usr/share/nginx/html
